version: '3'

services:
### PHP-FPM ##############################################
  php-fpm:
    container_name: php-fpm
    image: tamurayk/php-fpm:7.3.9
    volumes:
      - ./docker/php-fpm/index.php:/var/www/html/index.php

### NGINX Server #########################################
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/index.html:/var/www/html/index.html
    depends_on:
      - php-fpm
