version: '3'

services:
### NGINX Server #########################################
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/index.html:/var/www/html/index.html
