version: '3'

services:
  database:
    container_name: database
    image: mysql:5.7 #https://laravel.com/docs/7.x/database
    environment:
      MYSQL_DATABASE: webapp
      MYSQL_USER: webapp
      MYSQL_PASSWORD: Passw0rd
      MYSQL_ROOT_PASSWORD: Passw0rd
    ports:
      - "3306:3306"
    volumes:
      - laravel-template-database-data:/var/lib/mysql

  php-fpm:
    container_name: php-fpm
    image: tamurayk/php-fpm:7.3.9
    volumes:
      - ./src:/srv
    working_dir: /srv
    depends_on:
      - database

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/index.html:/var/www/html/index.html
    depends_on:
      - php-fpm

volumes:
  laravel-template-database-data:
    external:
      name: laravel-template-database-data
