<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::namespace('User')->group(function () {
    /**
     * Auth
     *
     * generated by `php artisan ui bootstrap --auth`
     */
    Auth::routes();
    // GET /home
    Route::get('/home', 'HomeController@index')->name('home');

    /**
     * OAuth Login
     */
    // GET /login/{provider}
    Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider')->name('oauth.login');
    // GET /login/{provider}/callback
    Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback')->name('oauth.callback');

    /**
     * Task
     */
    // GET /tasks
    Route::get('/tasks', 'Task\TaskIndexController')
        ->name('task.index')
        ->middleware('auth:user');

    // POST /task
    Route::post('/task', 'Task\TaskStoreController')
        ->name('task.store')
        ->middleware('auth:user');

    // DELETE /task/{task}
    Route::delete('/task/{task}', 'Task\TaskDestroyController')
        ->name('task.destroy')
        ->middleware('auth:user');
});


/**
 * admin
 */
Route::namespace('Admin')->prefix('admin')->group(function () {
    // GET /admin
    Route::get('/', function () {
        return view('admin.welcome');
    })->middleware('guest:admin');

    // GET /admin/home
    Route::get('/home', 'HomeController@index')
        ->middleware('auth:admin')
        ->name('admin.home');

    /**
     * Auth
     */
    Route::get('login', 'Auth\LoginController@showLoginForm')
        ->middleware('guest:admin')
        ->name('admin.login');
    Route::post('login', 'Auth\LoginController@login')
        ->middleware('guest:admin')
        ->name('admin.login');
    Route::post('logout', 'Auth\LoginController@logout')
        ->middleware('auth:admin')
        ->name('admin.logout');

    /**
     * User
     */
    // GET /admin/users
    Route::get('users', 'User\UserIndexController')
        ->middleware('auth:admin')
        ->name('admin.user.index');
});
