<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::namespace('User')->group(function () {
    /**
     * Auth
     *
     * generated by `php artisan ui bootstrap --auth`
     */
    Auth::routes();

    /**
     * OAuth Login
     */
    Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider')->name('oauth.login');
    Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback')->name('oauth.callback');

    /**
     * Require user auth
     */
    Route::middleware('auth:user')->group(function () {
        Route::get('/home', 'Home\HomeIndexController')->name('home.index');

        Route::get('/tasks', 'Task\TaskIndexController')->name('task.index');
        Route::post('/task', 'Task\TaskStoreController')->name('task.store');
        Route::delete('/task/{task}', 'Task\TaskDestroyController')->name('task.destroy');
    });

});

/**
 * admin
 */
Route::namespace('Admin')->prefix('admin')->group(function () {
    Route::middleware('guest:admin')->group(function () {
        Route::get('/', function () {
            return view('admin.welcome');
        });

        Route::get('login', 'Auth\LoginController@showLoginForm')->name('admin.login');
        Route::post('login', 'Auth\LoginController@login')->name('admin.login');
    });

    /**
     * Require user auth
     */
    Route::middleware('auth:admin')->group(function () {
        Route::post('logout', 'Auth\LoginController@logout')->name('admin.logout');

        Route::get('/home', 'Home\HomeIndexController')->name('admin.home.index');

        Route::get('/users', 'User\UserIndexController')->name('admin.user.index');

    });
});
