name: Laravel

on:
  push:
  pull_request:

jobs:
  laravel-tests:

    name: Laravel (PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }})
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.4']

    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: pdo_mysql
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: php composer.phar install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        sudo systemctl start mysql.service
        mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE IF NOT EXISTS testing;'
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: testing
        DB_TEST_HOST: 127.0.0.1
        DB_TEST_PORT: 3306
        DB_TEST_DATABASE: testing
        DB_TEST_USERNAME: root
        DB_TEST_PASSWORD: root
      run: vendor/bin/phpunit
